base_global_planner: global_planner/GlobalPlanner
GlobalPlanner:
  allow_unknown: true 
  default_tolerance: 0.0
  visualize_potential: false
  use_dijkstra: false 
  use_quadratic: true 
  use_grid_path: true 
  old_navfn_behavior: false 
  lethal_cost: 253 
  neutral_cost: 50 
  cost_factor: 3.0 
  publish_potential: true
  orientation_mode: 1 
  orientation_window_size: 1 
  outline_map: true 













   